from django.urls import path
from . import views
urlpatterns = [
    path("ec2_data/", views.EC2_instances_list.as_view(), name="ec2_data"),
    path("ec2_memory_data/",views.get_ec2_data,name="ec2-data"),
    path('api/ec2_memory_data/',views.EC2_Memory_utilization.as_view(),name='ec2_memory_data'),
    path('api/rds-data/', views.RDSData.as_view(), name='rds_data'),
    path('rds-data/', views.rds_data_view, name='rds_data_view'),
    #path('api/billing-data/', views.Get_Total_Bill.as_view(), name='billing_data_view'),
   # path('billing-data/', views.billing_data_view, name='billing_data'),
    path('api/demo-billing-data/', views.GetTotalBill.as_view(), name='demo-billing_data'),
    path('demo-billing-data/', views.demo_billing_data_view, name='demobilling_data'),
    path('api/secrets-data/', views.Secrets_data.as_view(), name='secrets-data'),
    path('secrets-data/', views.get_secret_data, name='secrets-data'),
    #path('detail-cost-data/', views.get_detail_cost_data, name='cost-data'),
    #path('api/detail-cost-data/', views.Get_Detailed_AWS_Cost.as_view(), name='detail-cost-data'),
    path('api/s3-detail-data/', views.Get_S3_Data.as_view(), name='s3-detail-data'),
    path('s3-detail-data/', views.get_detail_s3_data, name='s3-data'),
    path('api/ecr-detail-data/', views.Get_ECR_Data.as_view(), name='ecr-detail-data'),
    path('ecr-detail-data/', views.get_detail_ecr_data, name='ecr-data'),
    path('api/lambda-metrics/', views.LambdaMetricsView.as_view(), name='lambda_metrics-data'),
    path('lambda-metrics/',views.get_Lambda_Metrics, name='lambda_metrics'),
    path('api/detail-cost-data/', views.FetchAWSCostView.as_view(), name='fetch_aws_cost'),
    path('fetch-aws-cost/', views.get_detail_cost_data, name='fetch_aws_cost'),
    path('vpc-data/',views.get_VPC_data,name='vpc-data'),
    path('api/vpc-data/',views.Get_VPCData.as_view(), name='VPC-detail-data'),
    path('api/ecs-data/',views.Get_ECS_Data.as_view(),name='ecs-detailed-data'),
    path('ecs-data/',views.get_esc_data,name='ecs-data'),
    path('api/loadbalancer-data/',views.Get_load_balancer_Data.as_view(),name='loadbalancer-detailed-data'),
    path('loadbalancer-data/',views.get_loadbalnacer_data,name='loadbalancer-data'),
    path('ebs-data/',views.get_ebs_data,name='ebs-data'),
    path('api/ebs-data/',views.Get_EBS_Data.as_view(),name='ebs-detail-data'),
    path('api/waf-acl-data/',views.Get_WAF_Data.as_view(),name='waf-detail-data'),
    path('waf-acl-data/',views.get_waf_data,name='waf-data'),
    path('api/eip-data/',views.Get_Elastic_Ip.as_view(),name='eip-detail-data'),
    path('eip-data/',views.get_elastic_ip,name='eipdata'),

]
